name: node.js
on: [push, pull_request]
jobs:
  windows:
    name: Windows
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
        node: [12.x, 14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Update npm
      run: npm i -g npm

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test

